on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cprecioso/action-prepare-node@v1
      - run: yarn pack -o package.tgz
      - uses: actions/upload-artifact@v4
        with:
          name: package-tarball
          path: ./package.tgz

  test:
    runs-on: ubuntu-latest
    env:
      PLAYWRIGHT_BROWSERS_PATH: 0
    steps:
      - uses: actions/checkout@v4
      - uses: cprecioso/action-prepare-node@v1
      - run: yarn playwright install --with-deps chromium
      - run: yarn test

  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cprecioso/action-prepare-node@v1
      - run: yarn run build:docs
      - uses: actions/upload-pages-artifact@v3
        with:
          path: ./docs/

  deploy-docs:
    if: github.ref == 'refs/heads/main'
    needs:
      - build
      - test
      - build-docs
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
