on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cprecioso/action-prepare-node@v1
      - run: yarn pack -o package.tgz
      - uses: actions/upload-artifact@v4
        with:
          name: package-tarball
          path: ./package.tgz

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cprecioso/action-prepare-node@v1
      - run: yarn playwright install --with-deps chromium
      - run: yarn test
